In [1]:
%pip install 'pandas[performance,parquet]'

Collecting pandas[parquet,performance]
  Using cached pandas-2.3.1-cp313-cp313-macosx_11_0_arm64.whl.metadata (91 kB)
Collecting numpy>=1.26.0 (from pandas[parquet,performance])
  Downloading numpy-2.3.2-cp313-cp313-macosx_14_0_arm64.whl.metadata (62 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/dsevilla/prog/bdge/.venv/lib/python3.13/site-packages (from pandas[parquet,performance]) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas[parquet,performance])
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas[parquet,performance])
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting bottleneck>=1.3.6 (from pandas[parquet,performance])
  Using cached bottleneck-1.5.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (8.1 kB)
Collecting numba>=0.56.4 (from pandas[parquet,performance])
  Using cached numba-0.61.2-cp313-cp313-macosx_11_0_arm64.whl.metadata (2.7 kB)
Collecting numexpr>=2.8.4 (from pandas[parquet,performance])
  Using cached numexpr-2.11.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (9.0 kB)
Collecting pyarrow>=10.0.1 (from pandas[parquet,performance])
  Using cached pyarrow-21.0.0-cp313-cp313-macosx_12_0_arm64.whl.metadata (3.3 kB)
Collecting llvmlite<0.45,>=0.44.0dev0 (from numba>=0.56.4->pandas[parquet,performance])
  Using cached llvmlite-0.44.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (4.8 kB)
Collecting numpy>=1.26.0 (from pandas[parquet,performance])
  Using cached numpy-2.2.6-cp313-cp313-macosx_14_0_arm64.whl.metadata (62 kB)
Requirement already satisfied: six>=1.5 in /Users/dsevilla/prog/bdge/.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas[parquet,performance]) (1.17.0)
Using cached pandas-2.3.1-cp313-cp313-macosx_11_0_arm64.whl (10.7 MB)
Using cached bottleneck-1.5.0-cp313-cp313-macosx_11_0_arm64.whl (99 kB)
Using cached numba-0.61.2-cp313-cp313-macosx_11_0_arm64.whl (2.8 MB)
Using cached llvmlite-0.44.0-cp313-cp313-macosx_11_0_arm64.whl (26.2 MB)
Using cached numpy-2.2.6-cp313-cp313-macosx_14_0_arm64.whl (5.1 MB)
Using cached numexpr-2.11.0-cp313-cp313-macosx_11_0_arm64.whl (136 kB)
Using cached pyarrow-21.0.0-cp313-cp313-macosx_12_0_arm64.whl (31.2 MB)
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, pyarrow, numpy, llvmlite, pandas, numexpr, numba, bottleneck
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9/9 [bottleneck]9 [numba]]]
Successfully installed bottleneck-1.5.0 llvmlite-0.44.0 numba-0.61.2 numexpr-2.11.0 numpy-2.2.6 pandas-2.3.1 pyarrow-21.0.0 pytz-2025.2 tzdata-2025.2
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

## Descarga de los datos

En este caso los datos están disponibles en un repositorio git. Se pueden descargar también de la Web, pero se van actualizando. Los descargamos del repositorio git para que todos tengáis los mismos...

In [3]:
%%sh
test -e Posts.xml || \
  (curl -fsL https://github.com/dsevilla/bd2-data/raw/main/es.stackoverflow/es.stackoverflow.xml.tar.xz.00;
   curl -fsL https://github.com/dsevilla/bd2-data/raw/main/es.stackoverflow/es.stackoverflow.xml.tar.xz.01) |\
     tar Jxvf -

x Comments.xml
x Posts.xml
x Tags.xml
x Users.xml
x Votes.xml

In [ ]:
!ls -lh *.xml

## Inspección y procesado

Podemos inspeccionar los ficheros `.xml` para ver su contenido. Son XML, sí, pero ¿con qué formato?

Aunque se puede procesar el formato XML, lo que podemos ver es que cada entrada es exactamente una línea que comienza por "`  <row`", y que contiene un conjunto de atributos en formato "`atributo="valor"`". Si lo comprobamos, incluso no existirá ninguna comilla doble **dentro** de otra comilla doble, así que podemos extraer esos pares de forma fácil.

La siguiente función procesa el fichero XML línea a línea. Primero separa la parte inicial "`  <row`", y después procesa cada par clave/valor. Lo único que hace es construir el conjunto de atributos que hay en todas las entradas. Como vimos, cada fila contenía atributos diferentes. Queremos obtenerlos todos.

La función, en vez de retornar una lista, que ocuparía mucha memoria, retorna un generador, que es una lista (de pares clave-valor, un diccionario) que se va generando a medida que se recorre. Por eso utiliza la construcción `yield` de Python. Esto hace que la función se detenga, y cuando se le pide el siguiente elemento, continúa desde donde se quedó (*corrutina*).

In [ ]:
import re
import html
from collections.abc import Iterator

def generate_elements_from_lines(filename: str) -> Iterator[dict[str, str]]:

  # Al ser un formato XML, las cadenas están escapadas como XML/HTML. Hay que
  # desescapar las entidades HTML y reemplazar los saltos de línea por <br/>.
  # Los saltos de línea se cambian para hacer que en el CSV, cada entrada sea una
  # única línea.
  def unescape_html(text: str) -> str:
    return re.sub('\r?\n', '<br/>', html.unescape(text))

  def get_attrs(line: str) -> dict[str, str]:
    _, attrs = line.split("<row ", 2)
    return {m.group(1): unescape_html(m.group(2))
              for m in re.finditer(r"(\w+?)=\"(.*?)\"", attrs)}

  with open(filename, "r") as f:
    for line in f:
      if line.startswith("  <row"):
        yield get_attrs(line)

Hay que extraer el conjunto de atributos para saber qué columnas tendrá nuestra tabla/CSV o archivo JSON. Recuérdese que las dos primeras filas del archivo XML tenían diferentes atributos. ¿Cómo se haría esto?

In [5]:
def get_attr_set(iterator: Iterator[dict[str,str]]) -> set[str]:
  all_attrs: set[str] = set()
  for row in iterator:
    all_attrs.update(row.keys())
  return all_attrs

El conjunto de atributos es pues:

In [6]:
posts_attr_set: set[str] = get_attr_set(generate_elements_from_lines("Posts.xml"))
posts_attr_set

{'AcceptedAnswerId',
 'AnswerCount',
 'Body',
 'ClosedDate',
 'CommentCount',
 'CommunityOwnedDate',
 'ContentLicense',
 'CreationDate',
 'FavoriteCount',
 'Id',
 'LastActivityDate',
 'LastEditDate',
 'LastEditorDisplayName',
 'LastEditorUserId',
 'OwnerDisplayName',
 'OwnerUserId',
 'ParentId',
 'PostTypeId',
 'Score',
 'Tags',
 'Title',
 'ViewCount'}

Como sabemos que el atributo `Id` va a ser la clave primaria, lo ponemos al principio. Además, generamos una lista, no un conjunto, para que el orden sea conocido.

In [7]:
def id_as_first_attribute_sorted(all_attrs: set[str], id_name: str) -> list[str]:
  all_attrs.remove(id_name)
  return [id_name] + sorted(all_attrs)

In [8]:
posts_attrs: list[str] = id_as_first_attribute_sorted(posts_attr_set, 'Id')
posts_attrs

['Id',
 'AcceptedAnswerId',
 'AnswerCount',
 'Body',
 'ClosedDate',
 'CommentCount',
 'CommunityOwnedDate',
 'ContentLicense',
 'CreationDate',
 'FavoriteCount',
 'LastActivityDate',
 'LastEditDate',
 'LastEditorDisplayName',
 'LastEditorUserId',
 'OwnerDisplayName',
 'OwnerUserId',
 'ParentId',
 'PostTypeId',
 'Score',
 'Tags',
 'Title',
 'ViewCount']

## Escritura del formato CSV

El formato CSV está especificado en el estándar RFC 4180. https://www.ietf.org/rfc/rfc4180.txt. En general se puede utilizar la biblioteca `csv` de Python 3 y vamos a exportar una línea de cabecera con todos los campos. https://docs.python.org/3/library/csv.html.

Tendremos en cuenta que todas las filas tienen que tener las mismas columnas y en el mismo orden dado por `all_attrs`.

In [9]:
import csv

def write_csv(destfile: str, all_attrs: list[str], iterator: Iterator[dict[str,str]]) -> None:
  with open(destfile, 'w') as wf:
    cw = csv.writer(wf)

    # Escribir la línea de cabecera
    cw.writerow(all_attrs)

    # Recorrer el iterador
    for row in iterator:
      row_to_write: list[str] = [row.get(att, '') for att in all_attrs]
      cw.writerow(row_to_write)

In [10]:
write_csv('Posts.csv', posts_attrs, generate_elements_from_lines('Posts.xml'))

In [11]:
# Write the df dataframe to parquet file
from pandas import DataFrame

df_posts: DataFrame = pd.read_csv('Posts.csv', encoding='utf-8', header=0,
                 dtype={
                     'Id': 'Int64',
                     'AcceptedAnswerId': 'Int64',
                     'AnswerCount': 'Int16',
                     'Body': pd.StringDtype(),
                     'CommentCount': 'Int16',
                     'ContentLicense': pd.StringDtype(),
                     'FavoriteCount': 'Int32',
                     'LastEditorDisplayName': pd.StringDtype(),
                     'LastEditorUserId': 'Int64',
                     'OwnerDisplayName': pd.StringDtype(),
                     'OwnerUserId': 'Int64',
                     'ParentId': 'Int64',
                     'PostTypeId': 'Int8',
                     'Score': 'Int64',
                     'Tags': pd.StringDtype(),
                     'Title': pd.StringDtype(),
                     'ViewCount': 'Int64'
                 },
                 parse_dates=['ClosedDate', 'CommunityOwnedDate', 'CreationDate', 'LastActivityDate', 'LastEditDate'])

In [ ]:
# Fill NaN values with sensible defaults
from typing import Any

posts_defaults: dict[str, Any] = {
    'AnswerCount': 0,
    'CommentCount': 0,
    'FavoriteCount': 0,
    'Score': 0,
    'ViewCount': 0
}
df_posts.fillna(value=posts_defaults, inplace=True)

In [13]:
df_posts.head()

,Id,AcceptedAnswerId,AnswerCount,Body,ClosedDate,CommentCount,CommunityOwnedDate,ContentLicense,CreationDate,FavoriteCount,...,LastEditorDisplayName,LastEditorUserId,OwnerDisplayName,OwnerUserId,ParentId,PostTypeId,Score,Tags,Title,ViewCount
0,1,2,1,<p>Estoy creando un servicio usando <em>ASP.NE...,NaT,2,NaT,CC BY-SA 4.0,2015-10-29 15:56:52.933,0,...,user13558,<NA>,<NA>,23,<NA>,1,40,<.net><asp.net-web-api><asp.net>,La creación manual de un alias de ruta con un ...,780
1,2,<NA>,0,<p>He encontrado la solución.</p><br/><br/><p>...,NaT,2,NaT,CC BY-SA 3.0,2015-10-29 19:14:23.673,0,...,<NA>,<NA>,<NA>,23,1,2,31,<NA>,<NA>,0
2,3,9,3,"<p>Luego de ver cierto código, me he dado cuen...",NaT,1,NaT,CC BY-SA 3.0,2015-10-29 23:54:31.947,0,...,<NA>,20,<NA>,21,<NA>,1,20,<delphi>,¿Es igual utilizar .AsString que .Text para ob...,1035
3,4,<NA>,0,"<p><code>.AsString</code> devuelve el mismo ""<...",NaT,0,NaT,CC BY-SA 3.0,2015-10-30 00:45:47.640,0,...,<NA>,25,<NA>,24,3,2,6,<NA>,<NA>,0
4,5,208,7,<p>¿Cuál es la forma más eficiente de separar ...,NaT,1,NaT,CC BY-SA 3.0,2015-10-30 01:15:27.267,0,...,<NA>,729,<NA>,24,<NA>,1,37,<c++><string>,¿Cómo separar las palabras que contiene un str...,37867

In [14]:
df_posts.to_parquet('Posts.parquet', compression='gzip')

In [15]:
# Find the greatest Id in df_posts
max_id: int = df_posts['Id'].max()

# Split df_posts into three dataframes
df_posts1: DataFrame = df_posts[df_posts['Id'] <= max_id // 3]
df_posts2: DataFrame = df_posts[(df_posts['Id'] > max_id // 3) & (df_posts['Id'] <= 2 * max_id // 3)]
df_posts3: DataFrame = df_posts[df_posts['Id'] > 2 * max_id // 3]

In [16]:
# Write the three Posts parquet files
df_posts1.to_parquet('Posts1.parquet', compression='gzip')
df_posts2.to_parquet('Posts2.parquet', compression='gzip')
df_posts3.to_parquet('Posts3.parquet', compression='gzip')

In [17]:
votes_attr_set: set[str] = get_attr_set(generate_elements_from_lines("Votes.xml"))
votes_attr_set

{'BountyAmount', 'CreationDate', 'Id', 'PostId', 'UserId', 'VoteTypeId'}

In [18]:
votes_attrs: list[str] = id_as_first_attribute_sorted(votes_attr_set, 'Id')
votes_attrs

['Id', 'BountyAmount', 'CreationDate', 'PostId', 'UserId', 'VoteTypeId']

In [19]:
write_csv('Votes.csv', votes_attrs, generate_elements_from_lines('Votes.xml'))

In [20]:
# Write the df dataframe to parquet file
from pandas import DataFrame

df_votes: DataFrame = pd.read_csv('Votes.csv', encoding='utf-8', header=0,
                 dtype={
                     'Id': 'Int64',
                     'BountyAmount': 'Int64',
                     'PostId': 'Int64',
                     'UserId': 'Int64',
                     'VoteTypeId': 'Int8'
                 },
                 parse_dates=['CreationDate'])

In [21]:
df_votes.head()

   Id  BountyAmount CreationDate  PostId  UserId  VoteTypeId
0   1          <NA>   2015-10-29       1    <NA>           2
1   2          <NA>   2015-10-29       2    <NA>           2
2   3          <NA>   2015-10-30       3    <NA>           2
3   4          <NA>   2015-10-30       5    <NA>           2
4   5          <NA>   2015-10-30       7    <NA>           2

In [22]:
df_votes.to_parquet('Votes.parquet', compression='gzip')

In [23]:
tags_attr_set: set[str] = get_attr_set(generate_elements_from_lines("Tags.xml"))
tags_attr_set

{'Count', 'ExcerptPostId', 'Id', 'TagName', 'WikiPostId'}

In [24]:
tags_attrs: list[str] = id_as_first_attribute_sorted(tags_attr_set, 'Id')
tags_attrs

['Id', 'Count', 'ExcerptPostId', 'TagName', 'WikiPostId']

In [25]:
write_csv('Tags.csv', tags_attrs, generate_elements_from_lines('Tags.xml'))

In [26]:
# Write the df dataframe to parquet file
df_tags: DataFrame = pd.read_csv('Tags.csv', encoding='utf-8', header=0,
                 dtype={'Id': 'Int64',
                        'Count' : 'Int64',
                        'TagName' : pd.StringDtype(),
                        'ExcerptPostId': 'Int64',
                        'WikiPostId' : 'Int64' },
                 )

In [27]:
df_tags.head()

   Id  Count  ExcerptPostId          TagName  WikiPostId
0   1   1472            680             .net         679
1   2    293           3029  asp.net-web-api        3028
2   3    222             20           delphi          19
3   4   4704             15              c++          14
4   5   1491            585           string         584

In [ ]:
df_tags.dtypes

In [28]:
df_tags.to_parquet('Tags.parquet', compression='gzip')

In [29]:
users_attr_set: set[str] = get_attr_set(generate_elements_from_lines("Users.xml"))
users_attr_set

{'AboutMe',
 'AccountId',
 'CreationDate',
 'DisplayName',
 'DownVotes',
 'Id',
 'LastAccessDate',
 'Location',
 'Reputation',
 'UpVotes',
 'Views',
 'WebsiteUrl'}

In [30]:
users_attrs: list[str] = id_as_first_attribute_sorted(users_attr_set, 'Id')
users_attrs

['Id',
 'AboutMe',
 'AccountId',
 'CreationDate',
 'DisplayName',
 'DownVotes',
 'LastAccessDate',
 'Location',
 'Reputation',
 'UpVotes',
 'Views',
 'WebsiteUrl']

In [31]:
write_csv('Users.csv', users_attrs, generate_elements_from_lines('Users.xml'))

In [32]:
# Write the df dataframe to parquet file
df_users: DataFrame = pd.read_csv('Users.csv', encoding='utf-8', header=0,
                 dtype={'Id': 'Int64',
                        'DisplayName': pd.StringDtype(),
                        'Location' : pd.StringDtype(),
                        'UpVotes' : 'Int32',
                        'AboutMe' : pd.StringDtype(),
                        'Reputation' : 'Int64',
                        'AccountId' : 'Int64',
                        'DownVotes': 'Int32',
                        'WebsiteUrl' : pd.StringDtype(),
                        'Views' : 'Int64'},
                 parse_dates=['CreationDate','LastAccessDate'])

In [33]:
# Fill NaN values with sensible defaults
from typing import Any

users_defaults: dict[str, Any] = {
    'Views': 0
}
df_users.fillna(value=users_defaults, inplace=True)

In [ ]:
df_users.head()

In [ ]:
df_users.dtypes

In [34]:
df_users.to_parquet('Users.parquet', compression='gzip')

In [35]:
comments_attr_set: set[str] = get_attr_set(generate_elements_from_lines("Comments.xml"))
comments_attr_set

{'ContentLicense',
 'CreationDate',
 'Id',
 'PostId',
 'Score',
 'Text',
 'UserDisplayName',
 'UserId'}

In [36]:
comments_attrs: list[str] = id_as_first_attribute_sorted(comments_attr_set, 'Id')
comments_attrs

['Id',
 'ContentLicense',
 'CreationDate',
 'PostId',
 'Score',
 'Text',
 'UserDisplayName',
 'UserId']

In [37]:
write_csv('Comments.csv', comments_attrs, generate_elements_from_lines('Comments.xml'))

In [38]:
# Write the df dataframe to parquet file
df_comments: DataFrame = pd.read_csv('Comments.csv', encoding='utf-8', header=0,
                 dtype={'Id': 'Int64',
                        'ContentLicense' : pd.StringDtype(),
                        'PostId' : 'Int64',
                        'Text' : pd.StringDtype(),
                        'Score' : 'Int32',
                        'UserId' : 'Int64',
                        'UserDisplayName' : pd.StringDtype()
                        },
                 parse_dates=['CreationDate'])

In [ ]:
df_comments.head()

In [ ]:
df_comments.dtypes

In [39]:
df_comments.to_parquet('Comments.parquet', compression='gzip')